name: "brazil-cities"
services:
  brazil-cities-api:
    container_name: brazil-cities-api
    image: brazil-cities-api:latest
    environment:
      - CONNECTION_STRING_DB_POSTGRES=${CONNECTION_STRING_DB_POSTGRES}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        version: latest
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - brazil-cities-network
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgresDB
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - brazil-cities-network
  
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - brazil-cities-network

volumes:
  postgres-db-volume:
    external: false
networks:
  brazil-cities-network:
    driver: bridge