CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

CREATE TABLE "States" (
                          "Id" int GENERATED BY DEFAULT AS IDENTITY,
                          "StateAcronym" varchar NOT NULL,
                          "Name" varchar NOT NULL,
                          "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
                          "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
                          CONSTRAINT "PK_States" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
                          "Id" int GENERATED BY DEFAULT AS IDENTITY,
                          "Name" varchar NOT NULL,
                          "StateId" int NOT NULL,
                          "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
                          "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
                          CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
                          CONSTRAINT "FK_Cities_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cities_StateId" ON "Cities" ("StateId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240713205612_InitialDatabase', '8.0.7');

COMMIT;