name: CD Docker Hub
on:
  workflow_run:
    workflows: ["CI Build And Test"]
    branches: [main]
    types:
      - completed
jobs:
  docker_hub:
    name: Build and Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: lucasfm95
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          tags: 'lucasfm95/brazil-cities-api:latest'
          push: true